# Improve colors
set -g default-terminal 'screen-256color'

# Set scrollback buffer to 10000
set -g history-limit 10000

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
 
set -g @continuum-restore 'on'
# Change default shell to ZSH
set-option -g default-shell /bin/zsh

# Mouse support
set-option -g mouse on

# Act like a vim
setw -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Vim like resizing
bind H resize-pane -L 10
bind J resize-pane -D 10
bind K resize-pane -U 10
bind L resize-pane -R 10

# Change prefix
set -g prefix C-a
unbind C-b
bind a send-prefix

# Start indexing windows from 1
set -g base-index 1
set-window-option -g pane-base-index 1

# Renumber windows sequentially after closing any of them
set -g renumber-windows on

# Bind tmux config reload
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Bind split windows
bind | split-window -h
bind - split-window -v

set-option -g status-position top

BACKGROUND_COLOR='#1e1e1e'
TEXT_COLOR='#43A047'
SELECTION_COLOR='#444444'

set -g status-bg $BACKGROUND_COLOR
set -g status-fg $TEXT_COLOR

set -g window-status-current-format "#[bg=$SELECTION_COLOR,bold] 👀 #I: #W "
set -g window-status-format "#[fg=$TEXT_COLOR,bg=$BACKGROUND_COLOR] 🔎 #I: #W "
